import type { Metadata } from "next";
import { Funnel_Display } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "PokeDex",
  description: "Generated by Erick Ruiz",
};

const funnel = Funnel_Display({
  variable: "--font-funnel",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={funnel.variable}>
      <body>{children}</body>
    </html>
  );
}
